import fs from "fs";
import fsPromises from "fs/promises";
import path from "path";
import PDFDocument from "pdfkit";

const REPORT_DIRECTORY = path.resolve(
    "storage",
    "reports"
);

async function ensureDirectory() {

    await fsPromises.mkdir(
        REPORT_DIRECTORY,
        {
            recursive: true
        }
    );

}

function section(doc, title) {

    doc
        .moveDown()
        .fontSize(16)
        .fillColor("#003366")
        .text(title);

    doc.moveDown(0.5);

    doc
        .fontSize(10)
        .fillColor("black");

}

function line(doc, label, value) {

    doc.text(
        `${label}: ${value ?? "-"}`
    );

}

/*
|--------------------------------------------------------------------------
| Generate PDF
|--------------------------------------------------------------------------
*/

export async function generatePDF(

    reportData,

    generatedBy

) {

    await ensureDirectory();

    const filename =
        `report-${Date.now()}.pdf`;

    const filePath =
        path.join(
            REPORT_DIRECTORY,
            filename
        );

    return new Promise((resolve, reject) => {

        const doc = new PDFDocument({

            size: "A4",

            margin: 40

        });

        const stream =
            fs.createWriteStream(filePath);

        doc.pipe(stream);

        /*
        |--------------------------------------------------------------------------
        | Header
        |--------------------------------------------------------------------------
        */

        doc
            .fontSize(24)
            .fillColor("#0055AA")
            .text("HEMAP RMS", {
                align: "center"
            });

        doc
            .fontSize(18)
            .fillColor("black")
            .text(
                "Energy Management Report",
                {
                    align: "center"
                }
            );

        doc.moveDown();

        line(
            doc,
            "Generated",
            reportData.generatedAt
        );

        line(
            doc,
            "Generated By",
            generatedBy?.email ??
            generatedBy?.firstName ??
            "System"
        );

        /*
        |--------------------------------------------------------------------------
        | Dashboard
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Executive Summary"
        );

        const dashboard =
            reportData.dashboard || {};

        Object.entries(dashboard)
            .forEach(([key, value]) => {

                if (
                    typeof value !== "object"
                ) {

                    line(
                        doc,
                        key,
                        value
                    );

                }

            });

        /*
        |--------------------------------------------------------------------------
        | KPIs
        |--------------------------------------------------------------------------
        */

        section(doc, "KPIs");

        Object.entries(
            reportData.kpis || {}
        ).forEach(([k, v]) => {

            line(doc, k, v);

        });

        /*
        |--------------------------------------------------------------------------
        | Energy
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Energy Statistics"
        );

        Object.entries(
            reportData.energy || {}
        ).forEach(([k, v]) => {

            line(doc, k, v);

        });

        /*
        |--------------------------------------------------------------------------
        | Battery
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Battery"
        );

        Object.entries(
            reportData.battery || {}
        ).forEach(([k, v]) => {

            line(doc, k, v);

        });

        /*
        |--------------------------------------------------------------------------
        | Solar
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Solar"
        );

        Object.entries(
            reportData.solar || {}
        ).forEach(([k, v]) => {

            line(doc, k, v);

        });

        /*
        |--------------------------------------------------------------------------
        | Grid
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Grid"
        );

        Object.entries(
            reportData.grid || {}
        ).forEach(([k, v]) => {

            line(doc, k, v);

        });

        /*
        |--------------------------------------------------------------------------
        | Generator
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Generator"
        );

        Object.entries(
            reportData.generator || {}
        ).forEach(([k, v]) => {

            line(doc, k, v);

        });

        /*
        |--------------------------------------------------------------------------
        | Reliability
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Reliability"
        );

        Object.entries(
            reportData.reliability || {}
        ).forEach(([k, v]) => {

            line(doc, k, v);

        });

        /*
        |--------------------------------------------------------------------------
        | Forecast
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Forecast"
        );

        Object.entries(
            reportData.forecast || {}
        ).forEach(([k, v]) => {

            if (
                typeof v !== "object"
            ) {

                line(doc, k, v);

            }

        });

        /*
        |--------------------------------------------------------------------------
        | Optimization
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Optimization"
        );

        Object.entries(
            reportData.optimization || {}
        ).forEach(([k, v]) => {

            if (
                typeof v !== "object"
            ) {

                line(doc, k, v);

            }

        });

        /*
        |--------------------------------------------------------------------------
        | Alarms
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Alarm Summary"
        );

        Object.entries(
            reportData.alarms || {}
        ).forEach(([k, v]) => {

            line(doc, k, v);

        });

        /*
        |--------------------------------------------------------------------------
        | Weather
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "Weather"
        );

        Object.entries(
            reportData.weather || {}
        ).forEach(([k, v]) => {

            line(doc, k, v);

        });

        /*
        |--------------------------------------------------------------------------
        | AI Insights
        |--------------------------------------------------------------------------
        */

        section(
            doc,
            "AI Insights"
        );

        if (
            Array.isArray(
                reportData.insights
            )
        ) {

            reportData.insights.forEach(
                insight => {

                    doc.text(
                        `• ${insight}`
                    );

                }
            );

        }

        /*
        |--------------------------------------------------------------------------
        | Footer
        |--------------------------------------------------------------------------
        */

        doc.moveDown(2);

        doc
            .fontSize(8)
            .fillColor("gray")
            .text(
                "Generated automatically by HEMAP RMS",
                {
                    align: "center"
                }
            );

        doc.end();

        stream.on(
            "finish",
            () => {

                resolve({

                    filename,

                    filePath

                });

            }
        );

        stream.on(
            "error",
            reject
        );

    });

}

export default {

    generatePDF

};